[workspace]
resolver = "2"
members = [
    "node",
    "pallets/*",
    "runtime",
]

[workspace.package]
authors = ["Fenn Saji <fennsaji@gmail.com>"]
edition = "2021"

[profile.release]
panic = "unwind"
